import React, { useState, useEffect } from 'react';
import { User, Course } from '../types';
import * as db from '../services/db';
import { MOCK_COURSES } from '../constants';

const AdminDashboard: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [activeTab, setActiveTab] = useState<'pending' | 'seekers' | 'insights' | 'reports'>('pending');
  const [searchQuery, setSearchQuery] = useState('');
  const [grantingForUser, setGrantingForUser] = useState<string | null>(null);
  
  // For reports tab
  const [reports, setReports] = useState<string[]>([]);
  const [isLoadingReports, setIsLoadingReports] = useState(false);

  useEffect(() => {
    refreshData();
    const interval = setInterval(refreshData, 10000); 
    return () => clearInterval(interval);
  }, []);

  const refreshData = async () => {
    const data = await db.getStoredUsers();
    setUsers(data);
  };

  const handleApprove = async (userId: string, courseId: string) => {
    await db.approveUnlock(userId, courseId);
    await refreshData();
  };

  const handleLock = async (userId: string, courseId: string) => {
    if (window.confirm('Revoke access to this course?')) {
      await db.lockCourse(userId, courseId);
      await refreshData();
    }
  };

  const handleGrantAccess = async (userId: string, courseId: string) => {
    await db.approveUnlock(userId, courseId);
    setGrantingForUser(null);
    await refreshData();
  };

  const fetchReports = async () => {
    setIsLoadingReports(true);
    try {
      // Fetch the manifest generated by build.js
      const response = await fetch('/reports/manifest.json');
      if (response.ok) {
        const list = await response.json();
        setReports(list);
      } else {
        setReports([]);
      }
    } catch (e) {
      console.error("Failed to fetch reports manifest", e);
      setReports([]);
    } finally {
      setIsLoadingReports(false);
    }
  };

  useEffect(() => {
    if (activeTab === 'reports') {
      fetchReports();
    }
  }, [activeTab]);

  const pendingRequests = users.flatMap(user => 
    user.pendingUnlocks.map(courseId => ({
      userId: user.id,
      userEmail: user.email,
      courseId,
      courseTitle: MOCK_COURSES.find(c => c.id === courseId)?.title || 'Unknown Course'
    }))
  );

  const formatLastSeen = (isoString?: string) => {
    if (!isoString) return 'Never';
    const date = new Date(isoString);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    if (diff < 60000) return 'Just now';
    if (diff < 3600000) return `${Math.floor(diff/60000)}m ago`;
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const filteredUsers = users.filter(u => 
    u.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="max-w-7xl mx-auto animate-in fade-in duration-500 pb-20">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10">
        <div>
          <span className="text-indigo-600 font-black tracking-widest uppercase text-xs mb-2 block">Management Console</span>
          <h1 className="text-3xl sm:text-4xl font-black text-gray-900 tracking-tight leading-none">Administration</h1>
          <p className="text-gray-500 font-medium mt-2">Oversee student enrollment and system health.</p>
        </div>
        
        <div className="flex flex-wrap bg-white p-1.5 rounded-2xl shadow-sm border border-gray-100 overflow-x-auto">
          <button 
            onClick={() => setActiveTab('pending')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-[10px] uppercase tracking-wider flex items-center gap-2 flex-shrink-0 ${
              activeTab === 'pending' ? 'bg-indigo-700 text-white shadow-lg' : 'text-gray-400 hover:text-gray-600'
            }`}
          >
            Unlocks {pendingRequests.length > 0 && <span className="bg-red-500 text-white w-4 h-4 rounded-full flex items-center justify-center text-[8px]">{pendingRequests.length}</span>}
          </button>
          <button 
            onClick={() => setActiveTab('seekers')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-[10px] uppercase tracking-wider flex-shrink-0 ${
              activeTab === 'seekers' ? 'bg-indigo-700 text-white shadow-lg' : 'text-gray-400 hover:text-gray-600'
            }`}
          >
            Users
          </button>
          <button 
            onClick={() => setActiveTab('insights')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-[10px] uppercase tracking-wider flex-shrink-0 ${
              activeTab === 'insights' ? 'bg-indigo-700 text-white shadow-lg' : 'text-gray-400 hover:text-gray-600'
            }`}
          >
            Live Monitor
          </button>
          <button 
            onClick={() => setActiveTab('reports')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-[10px] uppercase tracking-wider flex-shrink-0 ${
              activeTab === 'reports' ? 'bg-indigo-700 text-white shadow-lg' : 'text-gray-400 hover:text-gray-600'
            }`}
          >
            <i className="fa-solid fa-file-zipper mr-1"></i> Reports
          </button>
        </div>
      </div>

      {activeTab === 'pending' && (
        <div className="bg-white rounded-[1.5rem] sm:rounded-[2rem] shadow-xl shadow-indigo-50 border border-gray-100 overflow-hidden">
          {pendingRequests.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead className="bg-gray-50/50 border-b border-gray-100">
                  <tr>
                    <th className="px-6 py-4 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Seeker</th>
                    <th className="px-6 py-4 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Course</th>
                    <th className="px-6 py-4 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {pendingRequests.map((req, idx) => (
                    <tr key={`${req.userId}-${req.courseId}-${idx}`} className="hover:bg-indigo-50/30 transition-colors">
                      <td className="px-6 py-4">
                        <div className="font-bold text-gray-900 text-sm">{req.userEmail}</div>
                        <div className="text-[9px] text-indigo-400 font-black tracking-widest uppercase">ID: {req.userId}</div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="font-bold text-indigo-700 text-sm">{req.courseTitle}</div>
                      </td>
                      <td className="px-6 py-4 text-right">
                        <button 
                          onClick={() => handleApprove(req.userId, req.courseId)}
                          className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-xl text-xs font-black shadow-lg transition-all"
                        >
                          Approve
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="p-20 sm:p-32 text-center">
               <div className="w-20 h-20 bg-gray-50 rounded-2xl flex items-center justify-center mx-auto mb-6 border-2 border-dashed border-gray-200">
                  <i className="fa-solid fa-check text-3xl text-gray-200"></i>
               </div>
               <h3 className="text-xl font-black text-gray-900">All Clear</h3>
               <p className="text-gray-500 max-w-xs mx-auto mt-2 text-sm">No pending enrollment requests.</p>
            </div>
          )}
        </div>
      )}

      {activeTab === 'seekers' && (
        <div className="space-y-6">
          <div className="relative max-w-md">
            <i className="fa-solid fa-search absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"></i>
            <input 
              type="text" 
              placeholder="Search by email..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-white border border-gray-200 rounded-2xl py-3 pl-12 pr-4 focus:ring-4 focus:ring-indigo-500/10 focus:border-indigo-500 outline-none transition-all shadow-sm"
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredUsers.map(user => (
              <div key={user.id} className="bg-white p-6 rounded-[2rem] border border-gray-100 shadow-xl shadow-indigo-50 hover:shadow-indigo-100 transition-all group relative overflow-hidden">
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-indigo-50 text-indigo-700 flex items-center justify-center font-black text-lg">
                      {user.email.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <h3 className="font-black text-gray-900 leading-tight truncate max-w-[120px]">{user.email}</h3>
                      <span className={`text-[8px] px-2 py-0.5 rounded-lg font-black uppercase tracking-widest mt-1 inline-block ${
                        user.role === 'ADMIN' ? 'bg-amber-100 text-amber-700' : 'bg-indigo-100 text-indigo-600'
                      }`}>
                        {user.role}
                      </span>
                    </div>
                  </div>
                  {user.role !== 'ADMIN' && (
                    <button 
                      onClick={() => setGrantingForUser(grantingForUser === user.id ? null : user.id)}
                      className="w-9 h-9 rounded-xl bg-gray-50 text-gray-400 hover:bg-indigo-600 hover:text-white transition-all flex items-center justify-center shadow-sm"
                    >
                      <i className={`fa-solid ${grantingForUser === user.id ? 'fa-xmark' : 'fa-plus'}`}></i>
                    </button>
                  )}
                </div>
                
                {grantingForUser === user.id && (
                  <div className="mb-6 p-4 bg-indigo-50 rounded-2xl border border-indigo-100 animate-in zoom-in duration-300">
                    <div className="text-[8px] font-black text-indigo-400 uppercase tracking-widest mb-3">Manually Unlock</div>
                    <div className="space-y-2">
                      {MOCK_COURSES.filter(c => !user.enrolledCourses.includes(c.id)).map(course => (
                        <button
                          key={course.id}
                          onClick={() => handleGrantAccess(user.id, course.id)}
                          className="w-full text-left px-3 py-2 bg-white rounded-lg text-[10px] font-bold text-gray-700 hover:bg-indigo-600 hover:text-white transition-all shadow-sm flex justify-between items-center"
                        >
                          {course.title}
                          <i className="fa-solid fa-plus text-[8px]"></i>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                <div className="space-y-3">
                  <div className="flex justify-between items-center text-[8px] font-black text-gray-400 uppercase tracking-widest">
                    <span>Enrolled ({user.enrolledCourses.length})</span>
                    <span className="text-indigo-400">{formatLastSeen(user.lastActive)}</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {user.enrolledCourses.length > 0 ? (
                      user.enrolledCourses.map(id => {
                        const course = MOCK_COURSES.find(c => c.id === id);
                        return (
                          <div key={id} className="group/tag flex items-center gap-2 text-[9px] bg-green-50 text-green-700 border border-green-100 pl-2 pr-1 py-1 rounded font-black">
                            {course?.title || 'Unknown'}
                            {user.role !== 'ADMIN' && (
                              <button onClick={() => handleLock(user.id, id)} className="w-3.5 h-3.5 rounded bg-green-200/50 hover:bg-red-600 hover:text-white flex items-center justify-center">
                                <i className="fa-solid fa-xmark text-[6px]"></i>
                              </button>
                            )}
                          </div>
                        );
                      })
                    ) : (
                      <div className="py-2 text-center w-full text-[9px] text-gray-300 italic">No courses unlocked.</div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === 'insights' && (
        <div className="bg-white rounded-[2rem] shadow-xl shadow-indigo-50 border border-gray-100 overflow-hidden">
          <div className="p-8 border-b border-gray-50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
             <div>
                <h3 className="text-xl font-black text-gray-900">Live Traffic</h3>
                <p className="text-xs text-gray-500 font-medium">Monitoring active learning sessions.</p>
             </div>
             <div className="flex gap-8">
                <div className="text-center">
                   <div className="text-xl font-black text-indigo-600">{users.length}</div>
                   <div className="text-[8px] text-gray-400 font-black uppercase tracking-widest">Students</div>
                </div>
                <div className="text-center">
                   <div className="text-xl font-black text-green-500">
                      {users.filter(u => u.lastActive && (new Date().getTime() - new Date(u.lastActive).getTime() < 300000)).length}
                   </div>
                   <div className="text-[8px] text-gray-400 font-black uppercase tracking-widest">Online (5m)</div>
                </div>
             </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-gray-50/50">
                <tr>
                  <th className="px-8 py-4 text-[9px] font-black text-gray-400 uppercase tracking-[0.2em]">Student</th>
                  <th className="px-8 py-4 text-[9px] font-black text-gray-400 uppercase tracking-[0.2em]">Last Active</th>
                  <th className="px-8 py-4 text-[9px] font-black text-gray-400 uppercase tracking-[0.2em]">Access Level</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {users.sort((a,b) => new Date(b.lastActive || 0).getTime() - new Date(a.lastActive || 0).getTime()).map(user => {
                  const isOnline = user.lastActive && (new Date().getTime() - new Date(user.lastActive).getTime() < 600000);
                  return (
                    <tr key={user.id} className="hover:bg-indigo-50/20 transition-all">
                      <td className="px-8 py-4">
                        <div className="flex items-center gap-3">
                          <div className={`w-2 h-2 rounded-full ${isOnline ? 'bg-green-500 animate-pulse' : 'bg-gray-200'}`}></div>
                          <div className="text-sm font-bold text-gray-900">{user.email}</div>
                        </div>
                      </td>
                      <td className="px-8 py-4">
                        <span className="text-xs font-bold text-gray-600">{formatLastSeen(user.lastActive)}</span>
                      </td>
                      <td className="px-8 py-4">
                         <span className={`text-[8px] px-2 py-0.5 rounded-full font-black uppercase tracking-widest ${
                           user.role === 'ADMIN' ? 'bg-amber-500 text-white' : 'bg-gray-100 text-gray-500'
                         }`}>
                           {user.role}
                         </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'reports' && (
        <div className="bg-white rounded-[2rem] shadow-xl shadow-indigo-50 border border-gray-100 overflow-hidden">
          <div className="p-8 border-b border-gray-50 flex items-center justify-between">
            <div>
              <h3 className="text-xl font-black text-gray-900">System Reports</h3>
              <p className="text-xs text-gray-500 font-medium">Download automatically collected .zip artifacts.</p>
            </div>
            <button 
              onClick={fetchReports} 
              className="p-2 text-indigo-600 hover:bg-indigo-50 rounded-lg transition-all"
            >
              <i className={`fa-solid fa-arrows-rotate ${isLoadingReports ? 'animate-spin' : ''}`}></i>
            </button>
          </div>
          
          <div className="p-8">
            {reports.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {reports.map((report, idx) => (
                  <div key={idx} className="flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-indigo-300 transition-all group">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 bg-indigo-100 text-indigo-600 rounded-xl flex items-center justify-center text-lg">
                        <i className="fa-solid fa-file-zipper"></i>
                      </div>
                      <div>
                        <div className="text-sm font-bold text-gray-800 line-clamp-1">{report}</div>
                        <div className="text-[10px] text-gray-400">Generated Artifact</div>
                      </div>
                    </div>
                    <a 
                      href={`/reports/${report}`} 
                      download 
                      className="w-10 h-10 bg-white border border-gray-100 text-gray-400 hover:text-indigo-600 hover:border-indigo-200 rounded-xl flex items-center justify-center transition-all shadow-sm"
                    >
                      <i className="fa-solid fa-download"></i>
                    </a>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-20">
                <div className="w-16 h-16 bg-gray-50 rounded-2xl flex items-center justify-center mx-auto mb-4 text-gray-200">
                  <i className="fa-solid fa-folder-open text-3xl"></i>
                </div>
                <p className="text-gray-400 text-sm font-medium">No reports found in /dist/reports.</p>
                <p className="text-[10px] text-gray-300 mt-2">Ensure your local build script is collecting reports from your Windows Temp directory.</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;